export const welcome = "welcome to akaecliptic.dev [version 0.1.0]";

export const asci = `MMMMMMMMMMMMMMMMMMMMMMO,.     ..;coOXWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWXo''...      .;o0NMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWNXXK0kdl;.    .;dXMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'    .oXMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.   'kNMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;   .lXMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.   :KM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.   cX
MMMMMMMMMMMMMXkooooxKMMMMMW0dooooooooookXMMWx.  .d
MMMMMMMMMMMXkc. ,;. ;xKW0do'       oXMMMNMMMk'    
MMMMMMMMMXkc. ,lKNd;. ;o'    cNMMMMMMMMMMMMMMk.   
MMMMMMMMMk.  .OMMMMX;        'dxxxxxxONMMMMMMK,   
KNMMMMMMMk.  .lkkkkd.                oXMMMMMMK,   
.:kKWMMMMk.   ',,;;'.        cXWWWWWWWMMMMMMM0'   
   'OMMMMk.  .OWWWWK;        'kOOOOOOOO0NMMMWd.  .
,   :XMMM0;..:KMMMMXo'.......,,,,,,,,,,lKMMM0,   :
x.  .oNMMWNNNNWMMMMMWNNNNNNNNNNNNNNNNNNNWMMX:   'O
No.  .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:   .xW
MNd.   ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk'   .kWM
MMWk'   .l0WMMMMMMMMMMMMMMMMMMMMMMMMMMNO:.   ;0WMM
MMMMKl.   .:xXWMMMMMMMMMMMMMMMMMMMMWKd;.   'dXMMMM
MMMMMW0l.    .:dOXNWMMMMMMMMMMWNKko;.    'dXMMMMMM
MMMMMMMWXx:.     .';cloooooolc;'.     .ckXMMMMMMMM
MMMMMMMMMMWKkl,.                 ..;okXWMMMMMMMMMM
MMMMMMMMMMMMMMNKxc,..        ..;lkKWMMMMMMMMMMMMMM
`;

export const greet = "enjoy your stay.";

export const user = "aka@akaecliptic.dev:/apps/solidjs$";
